Repository disciplinas-prof-Edeilson-UFT/proj-sist-2021-2, pull requests merged in 2021-11, with the labels that each got.

#14 R04 - [Cliente] Cadastrar Cliente
  assets/register_back.png
  lib/app/app_module.dart
  lib/app/global/models/entities/cliente.dart
  lib/app/global/widgets/app_bar/components/components_app_bar.dart
  lib/app/global/widgets/app_bar/components/desktop_app_bar.dart
  lib/app/global/widgets/app_bar/components/user_profile_options.dart
  lib/app/modules/auth/auth_page.dart
  lib/app/modules/auth/auth_store.dart
  lib/app/modules/auth/auth_store.g.dart
  lib/app/modules/register_client/pages/confirm_phone/confirm_phone_page.dart
  lib/app/modules/register_client/pages/register_client_page/register_client_page.dart
  lib/app/modules/register_client/register_client_module.dart
  lib/app/modules/register_client/register_client_repository.dart
  lib/app/modules/register_client/register_client_store.dart
  lib/app/modules/register_client/register_client_store.g.dart
  lib/app/modules/register_client/widgets/custom_submit_button.dart
  lib/app/modules/register_client/widgets/custom_text_field.dart
  lib/app/modules/update_client_data/update_client_data_module.dart
  lib/app/modules/update_client_data/update_client_data_page.dart
  lib/app/modules/update_client_data/update_client_data_store.dart
  lib/app/modules/update_client_data/update_client_data_store.g.dart
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: D: GP02, R: GP03

#15 [R06 e R07] Acompanhamento e Avaliação do Pedido
  assets/images/mc.png
  assets/images/track_order/gps_fundo.jpg
  assets/images/track_order/gps_fundo2.jpg
  assets/images/track_order/gps_img.png
  assets/images/track_order/gps_img2.jpg
  lib/app/app_module.dart
  lib/app/global/models/entities/order.dart
  lib/app/global/models/entities/rating.dart
  lib/app/global/models/enums/order_status.dart
  lib/app/global/repositories/order/order_repository.dart
  lib/app/global/repositories/order/order_repository_interface.dart
  lib/app/global/widgets/app_bar/components/mobile_app_bar.dart
  lib/app/global/widgets/footer_bar/components/desktop_footer_bar.dart
  lib/app/global/widgets/footer_bar/components/mobile_footer_bar.dart
  lib/app/global/widgets/footer_bar/components/tablet_footer_bar.dart
  lib/app/modules/cart/cart_store.dart
  lib/app/modules/cart/cart_store.g.dart
  lib/app/modules/cart/components/drawer/cart_drawer.dart
  lib/app/modules/cart/components/drawer/components/downside.dart
  lib/app/modules/cart/components/drawer/components/item_builder.dart
  lib/app/modules/cart/components/drawer/components/order_resume.dart
  lib/app/modules/cart/components/drawer/pages/empty_drawer.dart
  lib/app/modules/cart/components/drawer/pre_drawer_selector.dart
  lib/app/modules/cart/components/payment/components/order_container.dart
  lib/app/modules/cart/components/payment/components/pay_btn_builder.dart
  lib/app/modules/cart/components/payment/components/pay_item_builder.dart
  lib/app/modules/cart/components/payment/pages/payment_page.dart
  lib/app/modules/home/components/restaurant_card.dart
  lib/app/modules/home/components/restaurant_championship.dart
  lib/app/modules/home/schemas.dart
  lib/app/modules/order/components/details_page/components/background_image.dart
  lib/app/modules/order/components/details_page/components/detail_button.dart
  lib/app/modules/order/components/details_page/components/map_container.dart
  lib/app/modules/order/components/details_page/components/status_container.dart
  lib/app/modules/order/components/details_page/components/store_map_builder.dart
  lib/app/modules/order/components/details_page/components/store_name.dart
  lib/app/modules/order/components/details_page/pages/desktop_trackpage.dart
  lib/app/modules/order/components/details_page/pages/mobile_trackpage.dart
  lib/app/modules/order/components/details_page/pages/track_page.dart
  lib/app/modules/order/components/rating/rating_dialog.dart
  lib/app/modules/order/components/rating/rating_order.dart
  lib/app/modules/order/components/track/components/body_order.dart
  lib/app/modules/order/components/track/components/btn_order.dart
  lib/app/modules/order/components/track/components/cancel/cancel_order.dart
  lib/app/modules/order/components/track/components/cancel/class/cancel_store.dart
  lib/app/modules/order/components/track/components/cancel/class/cancel_store.g.dart
  lib/app/modules/order/components/track/components/empty_order.dart
  lib/app/modules/order/components/track/components/info_order.dart
  lib/app/modules/order/components/track/components/order_card.dart
  lib/app/modules/order/components/track/components/title_order_page.dart
  lib/app/modules/order/components/track/pages/desktop_order_page.dart
  lib/app/modules/order/components/track/pages/mobile_order_page.dart
  lib/app/modules/order/order_module.dart
  lib/app/modules/order/order_page.dart
  lib/app/modules/order/order_store.dart
  lib/app/modules/order/order_store.g.dart
  lib/app/modules/order/pages/tablet_oder_page.dart
  pubspec.lock
  pubspec.yaml
Labels: R: GP01, D: GP03

#18 R12 - [Lojista] Editar Perfil
  .vscode/settings.json
  android/.project
  android/.settings/org.eclipse.buildship.core.prefs
  assets/images/register/dragAndDropArea.png
  assets/images/restaurant_home/dragAndDropArea.png
  assets/images/restaurant_home/editProfile.png
  develop
  lib/app/global/models/entities/restaurant.dart
  lib/app/global/repositories/restaurant_home/profile/profile_repository.dart
  lib/app/global/repositories/restaurant_home/profile/profile_repository_interface.dart
  lib/app/global/widgets/side_bar/components_side_bar/components_side_bar.dart
  lib/app/global/widgets/side_bar/components_side_bar/desktop_side_bar.dart
  lib/app/global/widgets/side_bar/components_side_bar/mobile_side_bar.dart
  lib/app/global/widgets/side_bar/components_side_bar/tablet_side_bar.dart
  lib/app/modules/home/components/most_ordered.dart
  lib/app/modules/home/components/restaurant_grid.dart
  lib/app/modules/home/home_page.dart
  lib/app/modules/restaurant/pages/restaurant_tablet_page.dart
  lib/app/modules/restaurant_home/components/update_profile/components_profile_dialog.dart
  lib/app/modules/restaurant_home/components/update_profile/profile_alert_dialog.dart
  lib/app/modules/restaurant_home/components/update_profile/profile_picture_dialog.dart
  lib/app/modules/restaurant_home/components/update_profile/restaurant_profile_picture.dart
  lib/app/modules/restaurant_home/components/update_profile/update_formulary.dart
  lib/app/modules/restaurant_home/components/update_profile/update_profile.dart
  lib/app/modules/restaurant_home/components/update_profile/update_profile_dropdown.dart
  lib/app/modules/restaurant_home/pages/orders/orders_page.dart
  lib/app/modules/restaurant_home/restaurant_home_page.dart
  lib/app/modules/restaurant_home/restaurant_home_store.dart
  lib/app/modules/restaurant_home/restaurant_home_store.g.dart
  lib/app/modules/restaurant_register/pages/register_owner/owner_register_formulary.dart
  pubspec.lock
  pubspec.yaml
Labels: D: GP01, R: GP03

#20 R13 - [Lojista] Administrar dados sigilosos
  lib/app/global/models/entities/restaurant.dart
  lib/app/global/repositories/restaurant_home/profile/profile_repository.dart
  lib/app/global/repositories/restaurant_home/profile/profile_repository_interface.dart
  lib/app/global/widgets/bottom_app_bar/bottom_app_bar_mobile.dart
  lib/app/global/widgets/side_bar/components_side_bar/buttons_side_bar.dart
  lib/app/global/widgets/side_bar/components_side_bar/components_side_bar.dart
  lib/app/global/widgets/side_bar/components_side_bar/desktop_side_bar.dart
  lib/app/global/widgets/side_bar/components_side_bar/mobile_side_bar.dart
  lib/app/global/widgets/side_bar/components_side_bar/tablet_side_bar.dart
  lib/app/global/widgets/side_bar/custom_side_bar.dart
  lib/app/modules/cart/cart_store.g.dart
  lib/app/modules/home/components/most_ordered.dart
  lib/app/modules/home/components/restaurant_grid.dart
  lib/app/modules/home/home_page.dart
  lib/app/modules/order/components/track/components/cancel/class/cancel_store.dart
  lib/app/modules/order/components/track/components/cancel/class/cancel_store.g.dart
  lib/app/modules/order/components/track/components/empty_order.dart
  lib/app/modules/order/components/track/components/title_order_page.dart
  lib/app/modules/restaurant_home/components/add_product_card.dart
  lib/app/modules/restaurant_home/components/components_profile_dialog.dart
  lib/app/modules/restaurant_home/components/product_card.dart
  lib/app/modules/restaurant_home/components/product_page.dart
  lib/app/modules/restaurant_home/components/restaurant_dialog.dart
  lib/app/modules/restaurant_home/components/update_address/address_dialog.dart
  lib/app/modules/restaurant_home/components/update_address/address_formulary.dart
  lib/app/modules/restaurant_home/components/update_address/home_field.dart
  lib/app/modules/restaurant_home/components/update_profile/components_profile_dialog.dart
  lib/app/modules/restaurant_home/components/update_profile/profile_alert_dialog.dart
  lib/app/modules/restaurant_home/components/update_profile/update_formulary.dart
  lib/app/modules/restaurant_home/components/update_sensitive_data/management_dialog.dart
  lib/app/modules/restaurant_home/components/update_sensitive_data/management_formulary.dart
  lib/app/modules/restaurant_home/pages/plans/components/desktop_plan.dart
  lib/app/modules/restaurant_home/pages/plans/components/mobile_plan.dart
  lib/app/modules/restaurant_home/pages/plans/components/plan_selector.dart
  lib/app/modules/restaurant_home/pages/plans/restaurant_plan_page.dart
  lib/app/modules/restaurant_home/restaurant_home_module.dart
  lib/app/modules/restaurant_home/restaurant_home_store.dart
  lib/app/modules/restaurant_home/restaurant_home_store.g.dart
  lib/app/modules/restaurant_register/components/register_plans.dart
  pubspec.lock
  pubspec.yaml
Labels: D: GP01, R: GP03
